TARGET = make_lib

LIB_NAME = drv

SUB_DIRS =

PUBLIC_INC_PATH +=

EXTRA_C_DEFINES =

IMAGE_LAYOUT_FILE =

IMAGE_ENTRY_POINT =

ASM_SRC =

C_SRC =	nand_init.c \
	nand_rw.c   \
	uart.c      \
	intc.c

include $(MAKE_RULES)
